apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-postgres.yaml
  - analytics-db.yaml
  - airflow-postgres.yaml
  - airflow-config.yaml
  - airflow-apiserver.yaml
  - airflow-scheduler.yaml
  - airflow-dag-processor.yaml
  - airflow-init-job.yaml
  - analytics-db-fdw-init-job.yaml
  - airflow-rbac.yaml
  - ranking-batch-configmap.yaml
  - app-db-init-job.yaml
